version: "3.9" # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "55777:3000"
    links:
      - mongo
  mongojlg:
    image: "mongo"
    container_name: mongo
    ports:
      - "55888:27017"
    volumes:
      - "mongodata:/data/db"
volumes:
  mongodata:
